name: Build and Deploy to S3

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      
      - name: Build with Maven
        env:
          JDBC_URL: ${{ secrets.JDBC_URL }}
          JDBC_USERNAME: ${{ secrets.JDBC_USERNAME }}
          JDBC_PASSWORD: ${{ secrets.JDBC_PASSWORD }}
        run: ./mvnw clean package -P MySQL -DskipTests
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::424510830548:role/team1-github-s3-role
          aws-region: ap-northeast-2
      
      - name: Upload WAR to S3
        run: aws s3 cp target/petclinic.war s3://pet-clinic-apne2-bucket/ROOT.war --region ap-northeast-2