name: Build and Deploy to S3

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      
      - name: Build with Maven
        env:
          JDBC_URL: ${{ secrets.JDBC_URL }}
          JDBC_USERNAME: ${{ secrets.JDBC_USERNAME }}
          JDBC_PASSWORD: ${{ secrets.JDBC_PASSWORD }}
        run: ./mvnw clean package -P MySQL
      
      - name: Upload WAR to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 cp target/petclinic.war s3://pet-clinic-apne2-bucket/petclinic.war --region ap-northeast-2